import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  SessionProvider from "./session-provider";
import { getServerSession } from "next-auth";
import Navbar from "../components/nav-bar";
import RecoilRoot from "recoil";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};
// console.log(process.env.GOOGLE_CLIENT_ID)
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  const session = getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
      <Navbar />
        {children}
        </SessionProvider>
        </body>
    </html>
  );
}
